repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        name: autopep8
        language: python
        types: [python]
#        args: [-i, -v]
-   repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
